name: ğŸ¥ Remix Stacks Test

on:
  repository_dispatch:
    types: [release]

jobs:
  setup:
    name: Remix Stacks Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: âš’ï¸ Create new ${{ matrix.stack.name }} app with ${{ github.event.client_payload.ref }}
        run: |
          npx -y create-remix@${{ github.event.client_payload.ref }} ${{ matrix.stack.name }} --template ${{ matrix.stack.repo }} --typescript --no-install

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ matrix.stack.name }}
          useLockFile: false
          
      - name: Run `remix init`
        run: |
          cd ${{ matrix.stack.name }}
          npx remix init

      - name: ğŸ„ Copy test env vars
        run: |
          cd ${{ matrix.stack.name }}
          cp .env.example .env
          
      - name: Zip artifact
        run: zip release.zip ./${{ matrix.stack.name }} -r

      - name: ğŸ› Archive ${{ matrix.stack.name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive
          path: release.zip

  lint:
    name: â¬£ ESLint
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ› Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive
          
      - name: Unzip artifact
        run: unzip release.zip

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ matrix.stack.name }}

      - name: ğŸ”¬ Lint
        run: |
          cd ${{ matrix.stack.name }}
          npm run lint

  typecheck:
    name: Ê¦ TypeScript
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ› Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive
          
      - name: Unzip artifact
        run: unzip release.zip

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ matrix.stack.name }}

      - name: ğŸ” Type check
        run: |
          cd ${{ matrix.stack.name }}
          npm run typecheck --if-present

  vitest:
    name: âš¡ Vitest
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ› Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive
          
      - name: Unzip artifact
        run: unzip release.zip

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ matrix.stack.name }}

      - name: âš¡ Run vitest
        run: |
          cd ${{ matrix.stack.name }}
          npm run test -- --coverage

  cypress:
    name: âš«ï¸ Cypress
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ› Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive
          
      - name: Unzip artifact
        run: unzip release.zip

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ matrix.stack.name }}

      - name: ğŸ›  Setup Database
        run: |
          cd ${{ matrix.stack.name }}
          npx prisma migrate reset --force

      - name: âš™ï¸ Build
        run: |
          cd ${{ matrix.stack.name }}
          npm run build

      - name: ğŸŒ³ Cypress run
        uses: cypress-io/github-action@v3
        with:
          start: npm run start:mocks
          wait-on: "http://localhost:8811"
          working-directory: ${{ matrix.stack.name }}
        env:
          PORT: "8811"
